Repository its-harsshhh/DataStructures-and-Algorithms, pull requests merged in 2022-10, with the labels that each got.

#1 Create Find LCA in Binary Tree using RMQ.py
  Find LCA in Binary Tree using RMQ.py
Labels: Havktoberfest 2022 accepted

#3 Create Merge two sorted linked lists
  Circular Linked List Traversal.c
  Delete middle element of a stack.py
  Find LCA in Binary Tree using RMQ.py
  Maximum width of a Binary Tree.c
  Merge two sorted linked lists.c
  Reverse a Stack using Recursion .py
  Rotate a Linked List.c
  Sort a stack using a temporary stack.py
  Sort a stack using recursion.c
Labels: Havktoberfest 2022 accepted, Hacktoberfest 2022 accepted

#4 Pattern X
  Diamond Pattern.c
  Palindrome.c
  Remove duplicates from a sorted linked list.c
Labels: Hacktoberfest 2022 accepted

#5 Arranging the merge sort algorithm
  merge_sort.cpp
Labels: Hacktoberfest 2022 accepted

#6 Maximum Product Subarray Problem
  Maximum Product Subarray Problem.c
Labels: Hacktoberfest 2022 accepted

#7 Create dutchalgorithm.cpp
  dutchalgorithm.cpp
Labels: Hacktoberfest 2022 accepted

#8 Added Dijkstra's Algorithm implementation
  DijkstrasAlgorighm.java
Labels: Hacktoberfest 2022 accepted

#9 Print a given matrix in spiral form
  Print a given matrix in spiral form.py
Labels: Hacktoberfest 2022 accepted
